### HICORDIS Disease Dataset Preprocessing

This code reformats the HICORDIS disease dataset to average disease values for each disease by species across all observed size classes and locations.
Alternative approaches could be useful, but for the global-scale analysis we mostly want the aggregate values.

First, we'll import the HICORDIS dataset as a pandas DataFrame. This should let us group the rows according to an index column and average values of interest

In [19]:
from pandas import DataFrame,read_csv
from IPython.display import display,HTML
from os import listdir
from os.path import join

#Set input and output directories using join() to 
#correctly format the paths regardless of operating system
# (i.e. avoiding '/' vs. '\' issues on Mac & Linux vs. Windows)
input_dir = join("..","inputs")
output_dir = join("..","outputs")

hicordis_file = join(input_dir,"Caldwell_et_al_HICORDIS_data.txt")

#We have to set low_memory = False to avoid errors with columns with mixed types
#We set sep = "\t" since tab ("\t") characters delimit the columns
#in this dataset
hicordis_data = read_csv(hicordis_file,sep="\t",low_memory="False")

#NOTE: hicordis_data will be read in as a pandas DataFrame object

#Now let's show the first 5 rows as HTML
HTML(hicordis_data.head(5).to_html())

#### Disease by species - step 1 filter Table
OK, so now we have the data. We want to get an average amount of each disease, grouped by species. Species are denoted in the 'Species' header.

To simplify matters, let's first select only those columns from the DataFrame.

In [20]:
hicordis_data_reduced = hicordis_data[['Species','Disease_Type']].copy()
#Now let's show the first 5 rows as HTML
HTML(hicordis_data_reduced.head(15).to_html())

#### Disease by species - step 2 group table by species and count each Disease_Type
Now we want to group the table by Species, and count up the occurences of each type of disease

In [21]:
disease_by_species =\
  hicordis_data_reduced.groupby(['Species','Disease_Type'])

disease_counts = disease_by_species.Species.count()
print(disease_counts)

Species                 Disease_Type
Acropora_cytherea       Algal_overgrowth                 28
                        Bleaching                        61
                        Cyanobacteria                     3
                        Discoloration                     6
                        Growth_anomalies                 24
                        Macroalgal_overgrowth             2
                        No_Disease                     1563
                        Pigmentation_response             3
                        Predation                         3
                        Recently_denuded_skeleton         2
                        Tissue_Loss                      41
                        White_Syndrome                    6
Acropora_humilis        Bleaching                         2
                        No_Disease                       10
Acropora_nasuta         Algal_overgrowth                  6
                        No_Disease                        8
Acropora_paniculata     No_Disease                       21
                        Pigmentation_response             1
                        Predation                         1
Acropora_valida         No_Disease                        5
Cirrhipathes_anguina    No_Disease                        2
Cycloseris_vaughani     Algal_overgrowth                  1
                        Bleaching                         4
                        No_Disease                      168
Cyphastrea_agassizi     No_Disease                        3
Cyphastrea_ocellina     Algal_overgrowth                 20
                        Bleaching                       472
                        Discoloration                    44
                        Macroalgal_overgrowth             2
                        No_Disease                     1038
                                                       ...
Porites_rus             Tissue_Loss                       2
Porites_solida          Algal_Infection                   5
                        Algal_overgrowth                 11
                        Discoloration                     1
                        Endolithic_fungal_infection       1
                        No_Disease                       72
                        Pigmentation_response             9
                        Predation                         1
                        Tissue_Loss                       3
                        Trematodiasis                     1
Porites_sp.             Bleaching                         2
                        Growth_anomalies                 20
                        Tissue_Loss                       3
Psammocora_digitata     No_Disease                        1
Psammocora_haimeana     Algal_Infection                   1
                        Algal_overgrowth                  1
                        Bleaching                         1
                        No_Disease                      100
Psammocora_nierstraszi  Algal_overgrowth                  1
                        Discoloration                     1
                        No_Disease                       65
Psammocora_stellata     Algal_overgrowth                 64
                        Bleaching                        90
                        No_Disease                      770
                        Pigmentation_response             4
                        Predation                         6
Sarcothelia_edmondsoni  No_Disease                        8
Sinularia_densa         No_Disease                        2
Sponge                  No_Disease                        1
Zoanthus/Palythoa_sp.   No_Disease                        1
Name: Species, Length: 336, dtype: int64

The previous step gave us a count of disease types within each species. That's good news. We can easily now read out the frequency of each disease. However, other disease datasets like FRRP put the disease prevalence counts in the columns. We can use the unstack() method of our pandas DataFrame to put these data in that format.

In [22]:
disease_counts = disease_counts.unstack()





#Now let's show the first 5 rows as HTML
n_rows = 15
print(HTML(disease_counts.head(n_rows).to_html()))
HTML(disease_counts.head(15).to_html())

<IPython.core.display.HTML object>

That still leaves us with NA values. Since these are transect data and each disease was checked for in each transect, we should be able to treat unmeasured (NA or NaN) values as 0s. We do this with the pandas DataFrame method .fillna(0)

In [23]:
disease_counts = disease_counts.fillna(0)

#Now let's show the first 5 rows as HTML
HTML(disease_counts.head(5).to_html())

In [24]:
output_file = join(output_dir,"HICORDIS_disease_counts_by_species.txt")
disease_counts.to_csv(output_file, sep='\t')

#### Normalize columns by total

We may want to normalize the counts by the total to get percentages

In [25]:
# Sum up the total observation in each column,
# then divide each cell by the row total
# This will give us the % with each disease
normalized_disease_counts = disease_counts.div(disease_counts.sum(axis=1), axis=0)
#Now let's show the first 5 rows as HTML
HTML(normalized_disease_counts.head(5).to_html())

In [26]:
output_file = join(output_dir,"HICORDIS_disease_counts_by_species_normalized.txt")
normalized_disease_counts.to_csv(output_file, sep='\t')

### Done!

We now have normalized average prevalences for disease values per species.

Some notes and caveats:
1. Since each individual coral may have more than one disease, the normalized version may be approximate.
2. Some species names will not match other resources and will have to be adjusted manually (e.g. 'Zoanthus/Palythoa_sp.')